### ISSUE TITLE
Config doesn’t list arm6 support despite there being a published image to Docker hub

### ISSUE THREAD

**Issue by singe** [ParadoxAlarmInterface/hassio-repository#3]
I see Docker has arm6 images published but the config file doesn’t list arm6 support. The result is that hassOS running on a Pi Zero W lists the add on as not supported. Could you change the config file to list arm6 support?

**Comment by yozik04** [comment]
config file?

**Comment by yozik04** [comment]
I added `armhf`. Try one more time.

**Comment by singe** [comment]
That worked, thanks Jevgeni!
