### ISSUE TITLE
Log not displayed in addon page

### ISSUE THREAD

**Issue by singe** [ParadoxAlarmInterface/hassio-repository#4]
The Log area of the add-on (after installing to home assistant) shows blank. The add-on won't start for me, and hassOS makes getting to logs hard.

I wonder if:

"LOGGING_FILE": null,
https://github.com/ParadoxAlarmInterface/hassio-repository/blob/master/paradox_alarm_interface/config.json#L17

Has anything to do with it.

**Comment by yozik04** [comment]
I think HASS.IO shows logs from docker container. By default we write data to the console.

**Comment by singe** [comment]
Ah, this was because the docker image wasn't starting. I'll close this and open a separate more detailed issue.
