### ISSUE TITLE
Time zone not correct

### ISSUE THREAD

**Issue by cybertza** [ParadoxAlarmInterface/hassio-repository#7]
Hi is there a way to set the time zone on the docket for hass.io?

**Comment by yozik04** [comment]
Hass.io needs to have proper time zone. It will be passed to addons, according to docs.

**Comment by cybertza** [comment]
yea, my other addons seem to have the right time, this is what's confusing me?
so its around 10:30 am at the moment:
![image](https://user-images.githubusercontent.com/20600538/73132649-97ec4480-4026-11ea-9454-7813ed48b88e.png)
from traccar
![image](https://user-images.githubusercontent.com/20600538/73132659-a33f7000-4026-11ea-8c9e-87dda0aed3d1.png)
from pai
![image](https://user-images.githubusercontent.com/20600538/73132676-ca963d00-4026-11ea-93d2-a22e3840a12b.png)

**Comment by yozik04** [comment]
are you using Development version?

**Comment by yozik04** [comment]
Fixed in development version. Will be released in some days to master.

**Comment by cybertza** [comment]
I am not using dev, but will change to dev a bit later and let you know.

**Comment by cybertza** [comment]
Confirmed working now.

**Comment by yozik04** [comment]
Released in 2.0.0
