### ISSUE TITLE
Status unavailable after upgrade to 2.0.1 for devices

### ISSUE THREAD

**Issue by nardusleroux** [ParadoxAlarmInterface/hassio-repository#8]
After upgrading to 2.0.1 (date now correct and also serial port, thanks) I see the panel under MQTT integration and all entities, but no status shown for entities. Already removed addon and restarted HA and re-added, but entity status remains unavailable. 
Was there something that needs to be done for HA to understand the new status?
In logs and MQTT explorer, I see MQTT messages from panel, just not seeing status in HomeAssistant itself.

Environment is Raspbian Buster on PI4 with Docker CE. Hass.io runnning in Docker. 306 USB connected to serial port of SP6000.

**Comment by cybertza** [comment]
i have not had the same issue, 
have you looked with mqtt explorer what's going on, and if its updating?

**Comment by yozik04** [comment]
Try to remove mqtt integration in Hass and add it again.

**Comment by nardusleroux** [comment]
Thanks guys for suggestions. After lots more of troubleshooting, found that when host_network = true in config.json it works (local addon). Changed MQTT_HOST from 127.0.0.1 to real ip address and all ok now.
Thanks date and auto_uart working fine now.

**Comment by yozik04** [comment]
Added info to changelog. Thanks for sharing.
